Migrate to platform apis
enlyze/enlyze-python pull request #47
Opened 2024-08-15 16:07 UTC by denizs

2024-08-16 11:36 UTC, denizs commented on src/enlyze/api_client/client.py
This is the synthesis of the previously [single client](https://github.com/enlyze/enlyze-python/blob/acdaad88d34e53b074d524cef58b1fec61a06322/src/enlyze/timeseries_api/client.py) prior to the introduction of Production Runs.

2024-08-21 14:19 UTC, daniel-k requested changes
Haven't reviewed it yet, just noticed that coverage is missing for one line:

```
Name                                                               Stmts   Miss  Cover   Missing
------------------------------------------------------------------------------------------------
.tox/py/lib/python3.12/site-packages/enlyze/api_client/client.py      64      1    98%   149
```

2025-04-29 09:05 UTC, daniel-k commented on src/enlyze/api_client/models.py
> +    """
```suggestion
    """Base class for ENLYZE platform API object models using Pydantic

    All objects received from the ENLYZE platform API are passed into models that derive
    from this class and thus use Pydantic for schema definition and validation.

    """
```

2025-04-29 12:17 UTC, denizs commented on docs/api_client/client.rst
> +.. autoclass:: _PaginatedResponse
35cf875

2025-04-29 12:18 UTC, denizs commented on src/enlyze/api_client/models.py
> +    """
b0aaac4

2025-04-29 12:20 UTC, denizs commented on docs/api_client/index.rst
59e49d7

2025-04-29 12:22 UTC, denizs commented on src/enlyze/client.py
e87d2e9

2025-04-29 12:23 UTC, denizs commented on src/enlyze/api_client/client.py
> +            # if `data` is a dict then we treat it as only one object
c2b4f5b

2025-04-29 12:36 UTC, denizs commented on src/enlyze/api_client/models.py
> +class Machine(MachineBase):
Good call! This is because when this PR was submitted, the `machine` response field of `/api/v2/production-runs` was an expanded subset of the machine response, i.e. `name` and `uuid`, which in turn demanded this `MachineBase` model. 

However, this has long been refactored and `machine` now is a simple `uuid` reference, making `MachineBase` obsolete.

99a2f4f

2025-04-29 15:09 UTC, denizs commented on src/enlyze/api_client/models.py
> +class PlatformApiModel(BaseModel):
That actually was the result of the `MachineBase` model that did not have a `user_model` counterpart.
Now this is gone, 78a5a31 brings the `abstractmethod` back.

2025-05-05 09:10 UTC, daniel-k requested changes
Thank you for addressing my comments so far. What about these two?

- https://github.com/enlyze/enlyze-python/pull/47#discussion_r2065763788
- https://github.com/enlyze/enlyze-python/pull/47#discussion_r2065808976

2025-05-05 14:29 UTC, denizs commented on src/enlyze/api_client/client.py
> +    :param timeout: Global timeout for all HTTP requests sent to the ENLYZE platform API
Hm you're right, that really doesn't make any sense.

What do you think of d32a2e5?

2025-05-05 14:30 UTC, denizs commented on src/enlyze/api_client/client.py
> +            response_body = self.get(api_path, params=params, **kwargs)
Funny enough, this PR is older than the regression, so it's rather the other way around 😂

2025-05-05 15:11 UTC, daniel-k commented on src/enlyze/api_client/client.py
> +    :param timeout: Global timeout for all HTTP requests sent to the ENLYZE platform API
Lets roll with it :+1:

2025-05-05 15:12 UTC, daniel-k approved these changes

2025-05-05 15:49 UTC, merged